### PR TITLE
enable listening to demographics extract service bus

### PR DESCRIPTION
**Pull request by samplackett**
https://eaflood.atlassian.net/browse/DOC-428

### CODE REVIEW

**Review by kiranpal-atos — DISMISSED** [review]
LGTM!

**Review by GodsonLeigh — DISMISSED** [review]
you-may-proceed-tpau

**Review by GodsonLeigh — APPROVED** [review]
big-approve

**Review by GodsonLeigh — APPROVED** [review]
ok-approve

**Pull request merged**
